# config/requests.yaml
requests:
  - name: "example-get"
    method: GET
    url: "https://httpbin.org/get"
  - name: "example-post"
    method: POST
    url: "https://httpbin.org/post"
    headers:
      Content-Type: "application/json"
    body: '{"hello":"world"}'
